HTBox/MobileKidsIdApp

src/MCM.KidsIdApp/MCM.KidsIdApp.sln
Reverts HTBox/MobileKidsIdApp#48
=> Revert "46 fixing package files issues"

src/MCM.KidsIdApp/www/Scripts/Controllers/StaticPageCtrl.ts
Incorrect $inject in previous pull req https://github.com/HTBox/MobileKidsIdApp/issues/54
=> fix for issue 54

src/MCM.KidsIdApp/www/scripts/models/models.ts, src/MCM.KidsIdApp/www/scripts/models/shareSettings.ts
Initial attempt at typescript interfaces for data.
=> #34 - Typescript interfaces for data schema.

.gitignore
Adding Visual Studio Code's ".vscode" folder to .gitignore
=> Adding Visual Studio Code's ".vscode" folder to .gitignore

.gitignore, src/MCM.KidsIdApp/gulpfile.js, src/MCM.KidsIdApp/package.json
=> #85 Add sourcemaps that map typescript to javascript for debugging.

src/MCM.KidsIdApp/www/scripts/app.js, src/MCM.KidsIdApp/www/templates/login.html
=> 77 login bypass

src/MCM.KidsIdApp/www/scripts/app.js, src/MCM.KidsIdApp/www/scripts/controllers/LoginController.ts, src/MCM.KidsIdApp/www/scripts/definitions/AzureMobileServicesClient.d.ts, src/MCM.KidsIdApp/www/scripts/services/UserService.ts
#54 Moving login controller our of app.js and into its own file
=> Moving login controller our of app.js and into its own file

appveyor.yml, src/MCM.KidsIdApp/gulpfile.js
=> configure HockeyApp build

.gitignore, src/MCM.KidsIdApp/www/scripts/definitions/FileSystem.d.ts, src/MCM.KidsIdApp/www/scripts/definitions/services.d.ts, src/MCM.KidsIdApp/www/scripts/services/FileService.ts
=> #79 create FileSystem service for persisting data using the cordova File plugin.

src/MCM.KidsIdApp/bower.json, src/MCM.KidsIdApp/www/index.html, src/MCM.KidsIdApp/www/scripts/app.js
Just realized I left out some files that should've been in the last commit for the basic details screen.
=> #6 add some changes that were missed in previous commit.

src/MCM.KidsIdApp/bower.json, src/MCM.KidsIdApp/www/index.html, src/MCM.KidsIdApp/www/scripts/app.js, src/MCM.KidsIdApp/www/scripts/controllers/BasicDetailsController.ts, src/MCM.KidsIdApp/www/scripts/controllers/ChildProfileItemController.ts, src/MCM.KidsIdApp/www/scripts/controllers/ChildProfileListController.ts, src/MCM.KidsIdApp/www/scripts/controllers/PhotosController.ts, src/MCM.KidsIdApp/www/scripts/directives/FileSelectDir.ts, src/MCM.KidsIdApp/www/scripts/directives/StaticContentDir.ts, src/MCM.KidsIdApp/www/scripts/models/models.ts, src/MCM.KidsIdApp/www/scripts/services/ChildDataService.ts, src/MCM.KidsIdApp/www/scripts/services/DocumentService.ts, src/MCM.KidsIdApp/www/scripts/services/FileStorageService.ts, src/MCM.KidsIdApp/www/scripts/services/InMemoryStorageService.ts, src/MCM.KidsIdApp/www/scripts/services/serviceInterfaces.ts, src/MCM.KidsIdApp/www/templates/childprofileitem.html, src/MCM.KidsIdApp/www/templates/childprofilelist.html, src/MCM.KidsIdApp/www/templates/photos.html
Initial work on the child info menu and the photos page.  Working on my Android 4.3 phone, on an Android 5 emulator and in Ripple.
=> #29 Photos and #5 Child Info Menu

src/MCM.KidsIdApp/config.xml
Adding the cordova file plugin to the config.xml to prevent file errors
=> Add cordova-plugin-file to the config.xml

src/MCM.KidsIdApp/www/scripts/Controllers/DescriptionDetailsController.ts, src/MCM.KidsIdApp/www/scripts/definitions/jquery.d.ts, src/MCM.KidsIdApp/www/scripts/models/models.ts, src/MCM.KidsIdApp/www/scripts/services/ChildDataService.ts, src/MCM.KidsIdApp/www/templates/basicdetails.html, src/MCM.KidsIdApp/www/templates/descriptiondetails.html, src/MCM.KidsIdApp/www/templates/instructions/dna.partial.html
Affects #6 and #7
We are now going to leverage as much info from the phone contacts system as possible, so a Person is mostly a link to a contact. This results in a bunch of changes to the model.
Also this commit includes initial adds of the DescriptionDetails screen for a child.
=> Update model based on latest discussions

src/MCM.KidsIdApp/www/templates/instructions/amberalert.partial.html
=> acronym and spelling change; light editing

src/MCM.KidsIdApp/www/scripts/Controllers/DescriptionDetailsController.ts, src/MCM.KidsIdApp/www/scripts/models/models.ts, src/MCM.KidsIdApp/www/scripts/services/ChildDataService.ts, src/MCM.KidsIdApp/www/scripts/services/DocumentService.ts, src/MCM.KidsIdApp/www/scripts/services/serviceInterfaces.ts, src/MCM.KidsIdApp/www/templates/photos.html
#115 Update model to reflect current requirements
=> #115 Update model to reflect current requirements

src/MCM.KidsIdApp/www/scripts/Controllers/DistinguishingFeaturesController.ts, src/MCM.KidsIdApp/www/scripts/Controllers/PhysicalDetailsController.ts, src/MCM.KidsIdApp/www/scripts/app.js, src/MCM.KidsIdApp/www/scripts/controllers/ChildProfileItemController.ts, src/MCM.KidsIdApp/www/templates/distinguishingfeatures.html, src/MCM.KidsIdApp/www/templates/physicaldetails.html
#8 physical details screen implementation
=> #8 physical details screen implementation

src/MCM.KidsIdApp/gulpfile.js, src/MCM.KidsIdApp/package.json, src/MCM.KidsIdApp/spec/services/applicationDataService.spec.ts, src/MCM.KidsIdApp/www/scripts/app.js, src/MCM.KidsIdApp/www/scripts/services/ApplicationDataService.ts
=> #129 Fix bug with controllers being created twice.

src/MobileKidsIdApp/MobileKidsIdApp/MobileKidsIdApp/App.cs, src/MobileKidsIdApp/MobileKidsIdApp/MobileKidsIdApp/ViewModels/Landing.cs, src/MobileKidsIdApp/MobileKidsIdApp/MobileKidsIdApp/Views/Landing.xaml
=> Add navigation from landing to static content

src/MobileKidsIdApp/MobileKidsIdApp.sln, src/MobileKidsIdApp/MobileKidsIdApp/MobileKidsIdApp.Models/ApplicationData.cs, src/MobileKidsIdApp/MobileKidsIdApp/MobileKidsIdApp.Models/CareProvider.cs, src/MobileKidsIdApp/MobileKidsIdApp/MobileKidsIdApp.Models/Child.cs, src/MobileKidsIdApp/MobileKidsIdApp/MobileKidsIdApp.Models/ChildDetails.cs, src/MobileKidsIdApp/MobileKidsIdApp/MobileKidsIdApp.Models/DistinguishingFeature.cs, src/MobileKidsIdApp/MobileKidsIdApp/MobileKidsIdApp.Models/Family.cs, src/MobileKidsIdApp/MobileKidsIdApp/MobileKidsIdApp.Models/FamilyMember.cs, src/MobileKidsIdApp/MobileKidsIdApp/MobileKidsIdApp.Models/FileReference.cs, src/MobileKidsIdApp/MobileKidsIdApp/MobileKidsIdApp.Models/IContactReference.cs, src/MobileKidsIdApp/MobileKidsIdApp/MobileKidsIdApp.Models/IResourceReference.cs, src/MobileKidsIdApp/MobileKidsIdApp/MobileKidsIdApp.Models/MedicalNotes.cs, src/MobileKidsIdApp/MobileKidsIdApp/MobileKidsIdApp.Models/MobileKidsIdApp.Models.csproj, src/MobileKidsIdApp/MobileKidsIdApp/MobileKidsIdApp.Models/Person.cs, src/MobileKidsIdApp/MobileKidsIdApp/MobileKidsIdApp.Models/PhysicalDetails.cs, src/MobileKidsIdApp/MobileKidsIdApp/MobileKidsIdApp.Models/PreparationChecklist.cs, src/MobileKidsIdApp/MobileKidsIdApp/MobileKidsIdApp.Models/Properties/AssemblyInfo.cs, src/MobileKidsIdApp/MobileKidsIdApp/MobileKidsIdApp.Models/UserApplicationProfile.cs, src/MobileKidsIdApp/MobileKidsIdApp/MobileKidsIdApp.Models/UserIdentity.cs, src/MobileKidsIdApp/MobileKidsIdApp/MobileKidsIdApp/MobileKidsIdApp.csproj
=> #133 Re-add models project

src/MobileKidsIdApp/MobileKidsIdApp/MobileKidsIdApp/MobileKidsIdApp.csproj, src/MobileKidsIdApp/MobileKidsIdApp/MobileKidsIdApp/ViewModels/BindableObject.cs, src/MobileKidsIdApp/MobileKidsIdApp/MobileKidsIdApp/ViewModels/InstructionIndex.cs, src/MobileKidsIdApp/MobileKidsIdApp/MobileKidsIdApp/ViewModels/Landing.cs, src/MobileKidsIdApp/MobileKidsIdApp/MobileKidsIdApp/ViewModels/StaticContent.cs, src/MobileKidsIdApp/MobileKidsIdApp/MobileKidsIdApp/Views/InstructionIndex.xaml, src/MobileKidsIdApp/MobileKidsIdApp/MobileKidsIdApp/Views/StaticContent.xaml
#133 Add static content to app
=> #133 Add static content to app

src/MobileKidsIdApp/MobileKidsIdApp/MobileKidsIdApp.DataAccess/IApplicationDataProvider.cs, src/MobileKidsIdApp/MobileKidsIdApp/MobileKidsIdApp.DataAccess/IFamilyProvider.cs, src/MobileKidsIdApp/MobileKidsIdApp/MobileKidsIdApp.DataAccess/LocalStorage/ApplicationDataProvider.cs, src/MobileKidsIdApp/MobileKidsIdApp/MobileKidsIdApp.DataAccess/LocalStorage/FamilyProvider.cs, src/MobileKidsIdApp/MobileKidsIdApp/MobileKidsIdApp.DataAccess/MobileKidsIdApp.DataAccess.csproj, src/MobileKidsIdApp/MobileKidsIdApp/MobileKidsIdApp.DataAccess/packages.config, src/MobileKidsIdApp/MobileKidsIdApp/MobileKidsIdApp.Droid/MobileKidsIdApp.Droid.csproj, src/MobileKidsIdApp/MobileKidsIdApp/MobileKidsIdApp.Droid/Resources/Resource.Designer.cs, src/MobileKidsIdApp/MobileKidsIdApp/MobileKidsIdApp.Droid/packages.config, src/MobileKidsIdApp/MobileKidsIdApp/MobileKidsIdApp.Models/ApplicationData.cs, src/MobileKidsIdApp/MobileKidsIdApp/MobileKidsIdApp.Models/Family.cs, src/MobileKidsIdApp/MobileKidsIdApp/MobileKidsIdApp.UWP/project.json, src/MobileKidsIdApp/MobileKidsIdApp/MobileKidsIdApp.WinPhone/MobileKidsIdApp.WinPhone.csproj, src/MobileKidsIdApp/MobileKidsIdApp/MobileKidsIdApp.WinPhone/packages.config, src/MobileKidsIdApp/MobileKidsIdApp/MobileKidsIdApp.iOS/MobileKidsIdApp.iOS.csproj, src/MobileKidsIdApp/MobileKidsIdApp/MobileKidsIdApp.iOS/packages.config
#133 Most of the persistence code is implemented
=> #133 Most of the persistence code is implemented

src/MobileKidsIdApp/MobileKidsIdApp/MobileKidsIdApp/Properties/AssemblyInfo.cs, src/MobileKidsIdApp/MobileKidsIdApp/MobileKidsIdApp/ViewModels/BasicDetails.cs, src/MobileKidsIdApp/MobileKidsIdApp/MobileKidsIdApp/ViewModels/ChildprofileItem.cs, src/MobileKidsIdApp/MobileKidsIdApp/MobileKidsIdApp/ViewModels/ChildprofileList.cs, src/MobileKidsIdApp/MobileKidsIdApp/MobileKidsIdApp/ViewModels/StaticContent.cs, src/MobileKidsIdApp/MobileKidsIdApp/MobileKidsIdApp/Views/About.xaml, src/MobileKidsIdApp/MobileKidsIdApp/MobileKidsIdApp/Views/BasicDetails.xaml, src/MobileKidsIdApp/MobileKidsIdApp/MobileKidsIdApp/Views/ChildprofileItem.xaml, src/MobileKidsIdApp/MobileKidsIdApp/MobileKidsIdApp/Views/ChildprofileList.xaml, src/MobileKidsIdApp/MobileKidsIdApp/MobileKidsIdApp/Views/ChildprofileList.xaml.cs, src/MobileKidsIdApp/MobileKidsIdApp/MobileKidsIdApp/Views/DistinguishingFeatures.xaml, src/MobileKidsIdApp/MobileKidsIdApp/MobileKidsIdApp/Views/ForgotPassword.xaml, src/MobileKidsIdApp/MobileKidsIdApp/MobileKidsIdApp/Views/IdChecklist.xaml, src/MobileKidsIdApp/MobileKidsIdApp/MobileKidsIdApp/Views/InstructionIndex.xaml, src/MobileKidsIdApp/MobileKidsIdApp/MobileKidsIdApp/Views/Landing.xaml, src/MobileKidsIdApp/MobileKidsIdApp/MobileKidsIdApp/Views/Login.xaml, src/MobileKidsIdApp/MobileKidsIdApp/MobileKidsIdApp/Views/Photos.xaml, src/MobileKidsIdApp/MobileKidsIdApp/MobileKidsIdApp/Views/PhysicalDetails.xaml, src/MobileKidsIdApp/MobileKidsIdApp/MobileKidsIdApp/Views/ProfessionalCareProviders.xaml, src/MobileKidsIdApp/MobileKidsIdApp/MobileKidsIdApp/Views/Settings.xaml, src/MobileKidsIdApp/MobileKidsIdApp/MobileKidsIdApp/Views/StaticContent.xaml
=> Get basic child detail page working

src/MobileKidsIdApp/MobileKidsIdApp/MobileKidsIdApp.Models/ApplicationData.cs, src/MobileKidsIdApp/MobileKidsIdApp/MobileKidsIdApp.Models/BaseTypes/BusinessBase.cs, src/MobileKidsIdApp/MobileKidsIdApp/MobileKidsIdApp.Models/CareProvider.cs, src/MobileKidsIdApp/MobileKidsIdApp/MobileKidsIdApp.Models/Child.cs, src/MobileKidsIdApp/MobileKidsIdApp/MobileKidsIdApp.Models/ChildDetails.cs, src/MobileKidsIdApp/MobileKidsIdApp/MobileKidsIdApp.Models/DistinguishingFeature.cs, src/MobileKidsIdApp/MobileKidsIdApp/MobileKidsIdApp.Models/FamilyMember.cs, src/MobileKidsIdApp/MobileKidsIdApp/MobileKidsIdApp.Models/FileReference.cs, src/MobileKidsIdApp/MobileKidsIdApp/MobileKidsIdApp.Models/MedicalNotes.cs, src/MobileKidsIdApp/MobileKidsIdApp/MobileKidsIdApp.Models/MobileKidsIdApp.Models.csproj, src/MobileKidsIdApp/MobileKidsIdApp/MobileKidsIdApp.Models/Person.cs, src/MobileKidsIdApp/MobileKidsIdApp/MobileKidsIdApp.Models/PhysicalDetails.cs, src/MobileKidsIdApp/MobileKidsIdApp/MobileKidsIdApp.Models/PreparationChecklist.cs, src/MobileKidsIdApp/MobileKidsIdApp/MobileKidsIdApp.Models/UserApplicationProfile.cs, src/MobileKidsIdApp/MobileKidsIdApp/MobileKidsIdApp.Models/UserIdentity.cs, src/MobileKidsIdApp/MobileKidsIdApp/MobileKidsIdApp/ViewModels/ChildprofileItem.cs, src/MobileKidsIdApp/MobileKidsIdApp/MobileKidsIdApp/ViewModels/ChildprofileList.cs, src/MobileKidsIdApp/MobileKidsIdApp/MobileKidsIdApp/ViewModels/DistinguishingFeatures.cs, src/MobileKidsIdApp/MobileKidsIdApp/MobileKidsIdApp/Views/ChildprofileItem.xaml, src/MobileKidsIdApp/MobileKidsIdApp/MobileKidsIdApp/Views/ChildprofileList.xaml, src/MobileKidsIdApp/MobileKidsIdApp/MobileKidsIdApp/Views/DistinguishingFeatures.xaml
#9 Distinguishing features screen works, but the button to select a photo is not yet implemented.
=> #9 Distinguishing features screen

src/MobileKidsIdApp/MobileKidsIdApp/MobileKidsIdApp.Droid/MainApplication.cs, src/MobileKidsIdApp/MobileKidsIdApp/MobileKidsIdApp.Droid/MobileKidsIdApp.Droid.csproj, src/MobileKidsIdApp/MobileKidsIdApp/MobileKidsIdApp.Droid/packages.config, src/MobileKidsIdApp/MobileKidsIdApp/MobileKidsIdApp.UWP/project.json, src/MobileKidsIdApp/MobileKidsIdApp/MobileKidsIdApp.WinPhone/MobileKidsIdApp.WinPhone.csproj, src/MobileKidsIdApp/MobileKidsIdApp/MobileKidsIdApp.WinPhone/packages.config, src/MobileKidsIdApp/MobileKidsIdApp/MobileKidsIdApp.iOS/MobileKidsIdApp.iOS.csproj, src/MobileKidsIdApp/MobileKidsIdApp/MobileKidsIdApp.iOS/packages.config, src/MobileKidsIdApp/MobileKidsIdApp/MobileKidsIdApp/MobileKidsIdApp.csproj, src/MobileKidsIdApp/MobileKidsIdApp/MobileKidsIdApp/ViewModels/BasicDetails.cs, src/MobileKidsIdApp/MobileKidsIdApp/MobileKidsIdApp/ViewModels/ContactPicker.cs, src/MobileKidsIdApp/MobileKidsIdApp/MobileKidsIdApp/Views/BasicDetails.xaml, src/MobileKidsIdApp/MobileKidsIdApp/MobileKidsIdApp/Views/ContactPicker.xaml, src/MobileKidsIdApp/MobileKidsIdApp/MobileKidsIdApp/Views/ContactPicker.xaml.cs, src/MobileKidsIdApp/MobileKidsIdApp/MobileKidsIdApp/packages.config
#6 Sketch out code to select a contact
=> #6 Sketch out code to select a contact

src/MobileKidsIdApp/MobileKidsIdApp/MobileKidsIdApp/Controls/RepeaterView.cs, src/MobileKidsIdApp/MobileKidsIdApp/MobileKidsIdApp/MobileKidsIdApp.csproj, src/MobileKidsIdApp/MobileKidsIdApp/MobileKidsIdApp/Views/DistinguishingFeatures.xaml
#9 Add RepeaterView custom control for editing items in a list
=> #9 Add RepeaterView custom control for editing items in a list

src/MobileKidsIdApp/MobileKidsIdApp/MobileKidsIdApp.DataAccess/DataModels/CareProvider.cs, src/MobileKidsIdApp/MobileKidsIdApp/MobileKidsIdApp.Models/CareProvider.cs, src/MobileKidsIdApp/MobileKidsIdApp/MobileKidsIdApp/App.xaml, src/MobileKidsIdApp/MobileKidsIdApp/MobileKidsIdApp/App.xaml.cs, src/MobileKidsIdApp/MobileKidsIdApp/MobileKidsIdApp/Controls/RepeaterView.cs, src/MobileKidsIdApp/MobileKidsIdApp/MobileKidsIdApp/MobileKidsIdApp.csproj, src/MobileKidsIdApp/MobileKidsIdApp/MobileKidsIdApp/ViewModels/ChildprofileItem.cs, src/MobileKidsIdApp/MobileKidsIdApp/MobileKidsIdApp/ViewModels/ProfessionalCareProviders.cs, src/MobileKidsIdApp/MobileKidsIdApp/MobileKidsIdApp/Views/DistinguishingFeatures.xaml, src/MobileKidsIdApp/MobileKidsIdApp/MobileKidsIdApp/Views/ProfessionalCareProviders.xaml
=> Update data edit pages

src/MobileKidsIdApp/MobileKidsIdApp/MobileKidsIdApp.DataAccess/DataModels/PhysicalDetails.cs, src/MobileKidsIdApp/MobileKidsIdApp/MobileKidsIdApp.DataAccess/MockStorage/MockDb.cs, src/MobileKidsIdApp/MobileKidsIdApp/MobileKidsIdApp.Models/PhysicalDetails.cs, src/MobileKidsIdApp/MobileKidsIdApp/MobileKidsIdApp/MobileKidsIdApp.csproj, src/MobileKidsIdApp/MobileKidsIdApp/MobileKidsIdApp/ViewModels/ChildprofileItem.cs, src/MobileKidsIdApp/MobileKidsIdApp/MobileKidsIdApp/ViewModels/PhysicalDetails.cs, src/MobileKidsIdApp/MobileKidsIdApp/MobileKidsIdApp/ViewModels/PreparationChecklist.cs, src/MobileKidsIdApp/MobileKidsIdApp/MobileKidsIdApp/Views/PhysicalDetails.xaml, src/MobileKidsIdApp/MobileKidsIdApp/MobileKidsIdApp/Views/PreparationChecklist.xaml, src/MobileKidsIdApp/MobileKidsIdApp/MobileKidsIdApp/Views/PreparationChecklist.xaml.cs
Roughed in editors for two child property container objects. #163 #164
=> View Scaffolding for Physical Details, Preparation Checklist

src/MobileKidsIdApp/MobileKidsIdApp/MobileKidsIdApp.DataAccess/MobileKidsIdApp.DataAccess.csproj, src/MobileKidsIdApp/MobileKidsIdApp/MobileKidsIdApp.DataAccess/packages.config, src/MobileKidsIdApp/MobileKidsIdApp/MobileKidsIdApp.Droid/MobileKidsIdApp.Droid.csproj, src/MobileKidsIdApp/MobileKidsIdApp/MobileKidsIdApp.Droid/packages.config, src/MobileKidsIdApp/MobileKidsIdApp/MobileKidsIdApp.Models/MobileKidsIdApp.Models.csproj, src/MobileKidsIdApp/MobileKidsIdApp/MobileKidsIdApp.Models/packages.config, src/MobileKidsIdApp/MobileKidsIdApp/MobileKidsIdApp.UWP/project.json, src/MobileKidsIdApp/MobileKidsIdApp/MobileKidsIdApp.WinPhone/MobileKidsIdApp.WinPhone.csproj, src/MobileKidsIdApp/MobileKidsIdApp/MobileKidsIdApp.WinPhone/packages.config, src/MobileKidsIdApp/MobileKidsIdApp/MobileKidsIdApp.iOS/MobileKidsIdApp.iOS.csproj, src/MobileKidsIdApp/MobileKidsIdApp/MobileKidsIdApp.iOS/packages.config, src/MobileKidsIdApp/MobileKidsIdApp/MobileKidsIdApp/MobileKidsIdApp.csproj, src/MobileKidsIdApp/MobileKidsIdApp/MobileKidsIdApp/packages.config
=> Fix issue with ICloneable interface on save

src/MobileKidsIdApp/MobileKidsIdApp/MobileKidsIdApp.Models/PhysicalDetails.cs
#164 Set default measurement date to today
=> Set default measurement date to today

src/MobileKidsIdApp/MobileKidsIdApp/MobileKidsIdApp.DataAccess/LocalStorage/ApplicationDataProvider.cs, src/MobileKidsIdApp/MobileKidsIdApp/MobileKidsIdApp.Models/AppIdentity.cs, src/MobileKidsIdApp/MobileKidsIdApp/MobileKidsIdApp.Models/AppPrincipal.cs, src/MobileKidsIdApp/MobileKidsIdApp/MobileKidsIdApp.Models/MobileKidsIdApp.Models.csproj, src/MobileKidsIdApp/MobileKidsIdApp/MobileKidsIdApp/App.xaml.cs, src/MobileKidsIdApp/MobileKidsIdApp/MobileKidsIdApp/ViewModels/Landing.cs, src/MobileKidsIdApp/MobileKidsIdApp/MobileKidsIdApp/ViewModels/Login.cs, src/MobileKidsIdApp/MobileKidsIdApp/MobileKidsIdApp/ViewModels/Settings.cs, src/MobileKidsIdApp/MobileKidsIdApp/MobileKidsIdApp/Views/Landing.xaml, src/MobileKidsIdApp/MobileKidsIdApp/MobileKidsIdApp/Views/Login.xaml
Closes #33 and starts #158 Implement skeleton of login/logout functionality
=> #33 #158 Implement skeleton of login/logout functionality

src/MobileKidsIdApp/MobileKidsIdApp/MobileKidsIdApp.Droid/ActivityResultEventArgs.cs, src/MobileKidsIdApp/MobileKidsIdApp/MobileKidsIdApp.Droid/MainActivity.cs, src/MobileKidsIdApp/MobileKidsIdApp/MobileKidsIdApp.Droid/MobileKidsIdApp.Droid.csproj, src/MobileKidsIdApp/MobileKidsIdApp/MobileKidsIdApp.Droid/Services/PhotoPicker.cs, src/MobileKidsIdApp/MobileKidsIdApp/MobileKidsIdApp.UWP/MobileKidsIdApp.UWP.csproj, src/MobileKidsIdApp/MobileKidsIdApp/MobileKidsIdApp.UWP/Services/PhotoPicker.cs, src/MobileKidsIdApp/MobileKidsIdApp/MobileKidsIdApp.iOS/MobileKidsIdApp.iOS.csproj, src/MobileKidsIdApp/MobileKidsIdApp/MobileKidsIdApp.iOS/Services/PhotoPicker.cs, src/MobileKidsIdApp/MobileKidsIdApp/MobileKidsIdApp/MobileKidsIdApp.csproj, src/MobileKidsIdApp/MobileKidsIdApp/MobileKidsIdApp/Services/IPhotoPicker.cs, src/MobileKidsIdApp/MobileKidsIdApp/MobileKidsIdApp/ViewModels/ChildprofileItem.cs, src/MobileKidsIdApp/MobileKidsIdApp/MobileKidsIdApp/ViewModels/PhotoViewModel.cs, src/MobileKidsIdApp/MobileKidsIdApp/MobileKidsIdApp/ViewModels/Photos.cs, src/MobileKidsIdApp/MobileKidsIdApp/MobileKidsIdApp/Views/ChildprofileItem.xaml, src/MobileKidsIdApp/MobileKidsIdApp/MobileKidsIdApp/Views/ChildprofileList.xaml, src/MobileKidsIdApp/MobileKidsIdApp/MobileKidsIdApp/Views/Landing.xaml.cs, src/MobileKidsIdApp/MobileKidsIdApp/MobileKidsIdApp/Views/Photos.xaml, src/MobileKidsIdApp/MobileKidsIdApp/MobileKidsIdApp/packages.config
Looks like the photo picker needs to be implemented separately in all platforms.  I implemented UWP and Android.  The implementation for Android is using an ugly static variable for the MainActivity instance but I couldn't figure out a better way. #178
=> #178 Implement photos page and a photo picker service.

src/MobileKidsIdApp/MobileKidsIdApp/MobileKidsIdApp.DataAccess/MobileKidsIdApp.DataAccess.csproj, src/MobileKidsIdApp/MobileKidsIdApp/MobileKidsIdApp.DataAccess/packages.config, src/MobileKidsIdApp/MobileKidsIdApp/MobileKidsIdApp.Droid/MobileKidsIdApp.Droid.csproj, src/MobileKidsIdApp/MobileKidsIdApp/MobileKidsIdApp.Droid/packages.config, src/MobileKidsIdApp/MobileKidsIdApp/MobileKidsIdApp.Models/MobileKidsIdApp.Models.csproj, src/MobileKidsIdApp/MobileKidsIdApp/MobileKidsIdApp.Models/packages.config, src/MobileKidsIdApp/MobileKidsIdApp/MobileKidsIdApp.UWP/project.json, src/MobileKidsIdApp/MobileKidsIdApp/MobileKidsIdApp.WinPhone/MobileKidsIdApp.WinPhone.csproj, src/MobileKidsIdApp/MobileKidsIdApp/MobileKidsIdApp.WinPhone/packages.config, src/MobileKidsIdApp/MobileKidsIdApp/MobileKidsIdApp.iOS/MobileKidsIdApp.iOS.csproj, src/MobileKidsIdApp/MobileKidsIdApp/MobileKidsIdApp.iOS/packages.config, src/MobileKidsIdApp/MobileKidsIdApp/MobileKidsIdApp/MobileKidsIdApp.csproj, src/MobileKidsIdApp/MobileKidsIdApp/MobileKidsIdApp/packages.config
#181 Update to latest NuGet packages
=> #181 Update to latest NuGet packages

src/MobileKidsIdApp/MobileKidsIdApp/MobileKidsIdApp.Droid/MobileKidsIdApp.Droid.csproj, src/MobileKidsIdApp/MobileKidsIdApp/MobileKidsIdApp.Droid/Services/ContactPicker.cs, src/MobileKidsIdApp/MobileKidsIdApp/MobileKidsIdApp.Droid/Services/PhotoPicker.cs, src/MobileKidsIdApp/MobileKidsIdApp/MobileKidsIdApp.Droid/packages.config, src/MobileKidsIdApp/MobileKidsIdApp/MobileKidsIdApp.UWP/MobileKidsIdApp.UWP.csproj, src/MobileKidsIdApp/MobileKidsIdApp/MobileKidsIdApp.UWP/Services/ContactPicker.cs, src/MobileKidsIdApp/MobileKidsIdApp/MobileKidsIdApp.UWP/project.json, src/MobileKidsIdApp/MobileKidsIdApp/MobileKidsIdApp.WinPhone/MobileKidsIdApp.WinPhone.csproj, src/MobileKidsIdApp/MobileKidsIdApp/MobileKidsIdApp.WinPhone/packages.config, src/MobileKidsIdApp/MobileKidsIdApp/MobileKidsIdApp.iOS/MobileKidsIdApp.iOS.csproj, src/MobileKidsIdApp/MobileKidsIdApp/MobileKidsIdApp.iOS/Services/ContactPicker.cs, src/MobileKidsIdApp/MobileKidsIdApp/MobileKidsIdApp.iOS/packages.config, src/MobileKidsIdApp/MobileKidsIdApp/MobileKidsIdApp/MobileKidsIdApp.csproj, src/MobileKidsIdApp/MobileKidsIdApp/MobileKidsIdApp/Services/IContactPicker.cs, src/MobileKidsIdApp/MobileKidsIdApp/MobileKidsIdApp/ViewModels/BasicDetails.cs, src/MobileKidsIdApp/MobileKidsIdApp/MobileKidsIdApp/ViewModels/ChildprofileItem.cs, src/MobileKidsIdApp/MobileKidsIdApp/MobileKidsIdApp/ViewModels/ContactInfo.cs, src/MobileKidsIdApp/MobileKidsIdApp/MobileKidsIdApp/packages.config
Implement contact picker for UWP and Android.
=> #165 contact picker

src/MobileKidsIdApp/MobileKidsIdApp.sln, src/MobileKidsIdApp/MobileKidsIdApp/MobileKidsIdApp.Droid/MainActivity.cs, src/MobileKidsIdApp/MobileKidsIdApp/MobileKidsIdApp.Droid/MobileKidsIdApp.Droid.csproj, src/MobileKidsIdApp/MobileKidsIdApp/MobileKidsIdApp.Droid/Resources/Resource.Designer.cs, src/MobileKidsIdApp/MobileKidsIdApp/MobileKidsIdApp.Droid/app.config, src/MobileKidsIdApp/MobileKidsIdApp/MobileKidsIdApp.Droid/packages.config, src/MobileKidsIdApp/MobileKidsIdApp/MobileKidsIdApp.UWP/MainPage.xaml.cs, src/MobileKidsIdApp/MobileKidsIdApp/MobileKidsIdApp.UWP/project.json, src/MobileKidsIdApp/MobileKidsIdApp/MobileKidsIdApp.iOS/AppDelegate.cs, src/MobileKidsIdApp/MobileKidsIdApp/MobileKidsIdApp.iOS/Main.cs, src/MobileKidsIdApp/MobileKidsIdApp/MobileKidsIdApp.iOS/MobileKidsIdApp.iOS.csproj, src/MobileKidsIdApp/MobileKidsIdApp/MobileKidsIdApp.iOS/app.config, src/MobileKidsIdApp/MobileKidsIdApp/MobileKidsIdApp.iOS/packages.config, src/MobileKidsIdApp/MobileKidsIdApp/MobileKidsIdApp/App.xaml.cs, src/MobileKidsIdApp/MobileKidsIdApp/MobileKidsIdApp/MobileKidsIdApp.csproj, src/MobileKidsIdApp/MobileKidsIdApp/MobileKidsIdApp/Services/IAuthenticate.cs, src/MobileKidsIdApp/MobileKidsIdApp/MobileKidsIdApp/ViewModels/Login.cs, src/MobileKidsIdApp/MobileKidsIdApp/MobileKidsIdApp/app.config, src/MobileKidsIdApp/MobileKidsIdApp/MobileKidsIdApp/packages.config
#158 Call login providers to authenticate user
=> Login implementation

src/MobileKidsIdApp/MobileKidsIdApp/MobileKidsIdApp.Models/Friend.cs, src/MobileKidsIdApp/MobileKidsIdApp/MobileKidsIdApp.Models/FriendList.cs, src/MobileKidsIdApp/MobileKidsIdApp/MobileKidsIdApp/MobileKidsIdApp.csproj, src/MobileKidsIdApp/MobileKidsIdApp/MobileKidsIdApp/ViewModels/ChildprofileList.cs, src/MobileKidsIdApp/MobileKidsIdApp/MobileKidsIdApp/ViewModels/FriendList.cs
While not a complete implementation of #202, sets groundwork for contact picker invocation. Also corrects some minor unrelated screen flow issues.
=> 202 - First Installment

README.md
i noticed that the link to the Missing Children Minnesota website is broken
=> fix website url

src/MobileKidsIdApp.DataAccess/Encryption.cs, src/MobileKidsIdApp.DataAccess/MobileKidsIdApp.DataAccess.csproj, src/MobileKidsIdApp/MobileKidsIdApp.Android/MobileKidsIdApp.Android.csproj, src/MobileKidsIdApp/MobileKidsIdApp.Android/Resources/Resource.Designer.cs, src/MobileKidsIdApp/MobileKidsIdApp.UWP/MobileKidsIdApp.UWP.csproj, src/MobileKidsIdApp/MobileKidsIdApp.iOS/MobileKidsIdApp.iOS.csproj, src/MobileKidsIdApp/MobileKidsIdApp/MobileKidsIdApp.csproj
Closes #231 Restore use of PCLCrypto
=> Restore use of PCLCrypto

src/MobileKidsIdApp/MobileKidsIdApp.Android/MainActivity.cs, src/MobileKidsIdApp/MobileKidsIdApp.Android/Properties/AndroidManifest.xml, src/MobileKidsIdApp/MobileKidsIdApp.Android/Services/ContactPicker.cs, src/MobileKidsIdApp/MobileKidsIdApp/ViewModels/BasicDetails.cs, src/MobileKidsIdApp/MobileKidsIdApp/ViewModels/ChildprofileItem.cs, src/MobileKidsIdApp/MobileKidsIdApp/ViewModels/ContactPicker.cs
Just the Android changes right now.
=> Issue #226 - fix Contact Picker on Android

src/MobileKidsIdApp/MobileKidsIdApp.iOS/Info.plist
#206 Set iOS package name for signing.
=> #206 Set domain name for iOS signing

src/MobileKidsIdApp.Models/Child.cs, src/MobileKidsIdApp/MobileKidsIdApp/ViewModels/ChildprofileList.cs, src/MobileKidsIdApp/MobileKidsIdApp/Views/ChildprofileList.xaml
Added Child_DeleteSelf method to Child.cs. Added functionality to Remove a child in ChildProfileList; #213
=>  #213 Implemented functionality to remove a child in ChildProfileList

src/MobileKidsIdApp.DataAccess/MobileKidsIdApp.DataAccess.csproj, src/MobileKidsIdApp.Models/MobileKidsIdApp.Models.csproj, src/MobileKidsIdApp/MobileKidsIdApp.Android/MobileKidsIdApp.Android.csproj, src/MobileKidsIdApp/MobileKidsIdApp.UWP/MobileKidsIdApp.UWP.csproj, src/MobileKidsIdApp/MobileKidsIdApp.iOS/Info.plist, src/MobileKidsIdApp/MobileKidsIdApp.iOS/MobileKidsIdApp.iOS.csproj, src/MobileKidsIdApp/MobileKidsIdApp/MobileKidsIdApp.csproj
#206 Update app identity name
Closes #253 Update to latest CSLA preview that fixes bug with GraphMerger in iOS
=> Fix crash in iOS

src/MobileKidsIdApp.DataAccess/MobileKidsIdApp.DataAccess.csproj, src/MobileKidsIdApp.Models/MobileKidsIdApp.Models.csproj, src/MobileKidsIdApp/MobileKidsIdApp.Android/MobileKidsIdApp.Android.csproj, src/MobileKidsIdApp/MobileKidsIdApp.UWP/MobileKidsIdApp.UWP.csproj, src/MobileKidsIdApp/MobileKidsIdApp.iOS/MobileKidsIdApp.iOS.csproj, src/MobileKidsIdApp/MobileKidsIdApp/MobileKidsIdApp.csproj, src/MobileKidsIdApp/MobileKidsIdApp/ViewModels/Photos.cs
#261 Update packages/code prior to GiveCamp
=> Update packages/code prior to GiveCamp

src/MobileKidsIdApp/MobileKidsIdApp.iOS/AppDelegate.cs
#260 Update iOS authentication
=> Update iOS authentication

src/MobileKidsIdApp.DataAccess/IFamilyProvider.cs, src/MobileKidsIdApp.DataAccess/LocalStorage/FamilyProvider.cs, src/MobileKidsIdApp.DataAccess/MockStorage/FamilyProvider.cs, src/MobileKidsIdApp.Models/AppIdentity.cs, src/MobileKidsIdApp.Models/FamilyExists.cs, src/MobileKidsIdApp.sln, src/MobileKidsIdApp/MobileKidsIdApp/App.xaml, src/MobileKidsIdApp/MobileKidsIdApp/ViewModels/Login.cs, src/MobileKidsIdApp/MobileKidsIdApp/Views/Login.xaml
#260 Verify new pw; show errors for bad pw values
=> Verify new pw; show errors for bad pw values

src/MobileKidsIdApp/MobileKidsIdApp/App.xaml
=> Update header text style

src/MobileKidsIdApp.DataAccess/DataModels/Child.cs, src/MobileKidsIdApp.Models/Child.cs, src/MobileKidsIdApp/MobileKidsIdApp/ViewModels/ChildprofileList.cs
Closes #267, closes #270 
Data wasn't persisting consistently due to a bug in how the result of SaveAsync was (not) being properly merged into the existing Model.
=> Fix persistence issues

src/MobileKidsIdApp/MobileKidsIdApp.iOS/MobileKidsIdApp.iOS.csproj
#206 Change to automatic provisioning for development/debugging
=> Change to automatic provisioning for development/debugging

src/MobileKidsIdApp.Models/CareProvider.cs, src/MobileKidsIdApp.Models/CareProviderList.cs, src/MobileKidsIdApp.Models/DistinguishingFeature.cs, src/MobileKidsIdApp.Models/DistinguishingFeatureList.cs, src/MobileKidsIdApp.Models/FamilyMember.cs, src/MobileKidsIdApp.Models/FamilyMemberList.cs, src/MobileKidsIdApp.Models/FileReference.cs, src/MobileKidsIdApp.Models/FileReferenceList.cs
#269 Fix all the AddNewCore code so child objects are properly added to collections
=> Fix app crashes when adding child objects to pages

src/MobileKidsIdApp.Models.Test/BasicDetailsTests.cs, src/MobileKidsIdApp.Models.Test/CareProviderTests.cs, src/MobileKidsIdApp.Models.Test/FamilyTests.cs, src/MobileKidsIdApp.Models.Test/MedicalNotesTests.cs, src/MobileKidsIdApp.Models.Test/MobileKidsIdApp.Models.Test.csproj, src/MobileKidsIdApp.Models.Test/PreparednessChecklistTests.cs, src/MobileKidsIdApp.Models/AppIdentity.cs, src/MobileKidsIdApp.Models/ApplicationContextManager.cs, src/MobileKidsIdApp.sln, src/MobileKidsIdApp/MobileKidsIdApp/App.xaml.cs
=> Fix issues with persisting child details data

src/MobileKidsIdApp.DataAccess/IFamilyProvider.cs, src/MobileKidsIdApp.DataAccess/LocalStorage/FamilyProvider.cs, src/MobileKidsIdApp.DataAccess/MockStorage/FamilyProvider.cs, src/MobileKidsIdApp.DataAccess/MockStorage/MockDb.cs, src/MobileKidsIdApp.Models.Test/BasicDetailsTests.cs, src/MobileKidsIdApp.Models.Test/CareProviderTests.cs, src/MobileKidsIdApp.Models.Test/DistinguishingFeaturesTests.cs, src/MobileKidsIdApp.Models.Test/FamilyTests.cs, src/MobileKidsIdApp.Models.Test/MedicalNotesTests.cs, src/MobileKidsIdApp.Models.Test/PhotosTests.cs, src/MobileKidsIdApp.Models.Test/PhysicalDetailsTests.cs, src/MobileKidsIdApp.Models.Test/PreparednessChecklistTests.cs, src/MobileKidsIdApp.Models/AppIdentity.cs, src/MobileKidsIdApp.Models/DistinguishingFeature.cs, src/MobileKidsIdApp.Models/DistinguishingFeatureList.cs, src/MobileKidsIdApp.Models/FileReference.cs, src/MobileKidsIdApp/MobileKidsIdApp.iOS/MobileKidsIdApp.iOS.csproj
#300 Ensure LocalStorage DAL manages files correctly
=> Ensure LocalStorage DAL manages files correctly

src/MobileKidsIdApp.Models.Test/DocumentsTests.cs, src/MobileKidsIdApp.Models.Test/FamilyMembersTests.cs, src/MobileKidsIdApp.Models.Test/FriendsTests.cs, src/MobileKidsIdApp.Models/FamilyMember.cs
#300 Add persistence tests for Documents, FamilyMembers, Friends
=> Add persistence tests for Documents, FamilyMembers, Friends

src/MobileKidsIdApp/MobileKidsIdApp/ViewModels/ChildprofileItem.cs, src/MobileKidsIdApp/MobileKidsIdApp/ViewModels/ChildprofileList.cs, src/MobileKidsIdApp/MobileKidsIdApp/ViewModels/ViewModelBase.cs, src/MobileKidsIdApp/MobileKidsIdApp/Views/ChildprofileItem.xaml.cs
#318 Fix problem with adding new children to family
=> Fix problem with adding new children to family

src/MobileKidsIdApp.Models.Test/FamilyTests.cs, src/MobileKidsIdApp.Models/BaseTypes/BusinessBase.cs, src/MobileKidsIdApp.Models/Child.cs
=> Minor code changes related to persistence

src/MobileKidsIdApp/MobileKidsIdApp/Controls/RepeaterView.cs, src/MobileKidsIdApp/MobileKidsIdApp/Views/ProfessionalCareProviders.xaml
#303 Fix binding issue with care provider details
=> Fix binding issue with care provider details

src/MobileKidsIdApp/MobileKidsIdApp.Android/Services/PhotoPicker.cs, src/MobileKidsIdApp/MobileKidsIdApp.UWP/Services/PhotoPicker.cs, src/MobileKidsIdApp/MobileKidsIdApp.iOS/MobileKidsIdApp.iOS.csproj, src/MobileKidsIdApp/MobileKidsIdApp.iOS/Services/PhotoPicker.cs, src/MobileKidsIdApp/MobileKidsIdApp/ViewModels/PhotoViewModel.cs, src/MobileKidsIdApp/MobileKidsIdApp/ViewModels/Photos.cs, src/MobileKidsIdApp/MobileKidsIdApp/ViewModels/ViewModelBase.cs
=> Photo picker

src/MobileKidsIdApp/MobileKidsIdApp/ViewModels/BasicDetails.cs, src/MobileKidsIdApp/MobileKidsIdApp/Views/BasicDetails.xaml
=> Fixes the Contact Picker on Basic Info

src/MobileKidsId.PdfGenerationAppService/ApplicationInsights.config, src/MobileKidsId.PdfGenerationAppService/MobileKidsId.PdfGenerationAppService.csproj, src/MobileKidsId.PdfGenerationAppService/Web.config, src/MobileKidsId.PdfGenerationAppService/packages.config, src/MobileKidsIdApp.DataAccess/MobileKidsIdApp.DataAccess.csproj, src/MobileKidsIdApp.Models.Test/MobileKidsIdApp.Models.Test.csproj, src/MobileKidsIdApp.Models/MobileKidsIdApp.Models.csproj, src/MobileKidsIdApp/MobileKidsIdApp.Android/MobileKidsIdApp.Android.csproj, src/MobileKidsIdApp/MobileKidsIdApp.Android/Resources/Resource.Designer.cs, src/MobileKidsIdApp/MobileKidsIdApp.UWP/MobileKidsIdApp.UWP.csproj, src/MobileKidsIdApp/MobileKidsIdApp.iOS/MobileKidsIdApp.iOS.csproj, src/MobileKidsIdApp/MobileKidsIdApp/MobileKidsIdApp.csproj
=> #336 Update dependencies

src/MobileKidsIdApp.Models.Test/FriendsTests.cs, src/MobileKidsIdApp.Models/CareProvider.cs, src/MobileKidsIdApp.Models/Child.cs, src/MobileKidsIdApp.Models/ChildDetails.cs, src/MobileKidsIdApp.Models/DistinguishingFeature.cs, src/MobileKidsIdApp.Models/FamilyMember.cs, src/MobileKidsIdApp.Models/Friend.cs, src/MobileKidsIdApp.Models/PreparationChecklist.cs, src/MobileKidsIdApp/MobileKidsIdApp.Android/Properties/AndroidManifest.xml, src/MobileKidsIdApp/MobileKidsIdApp.Android/Services/ContactPicker.cs, src/MobileKidsIdApp/MobileKidsIdApp/App.xaml, src/MobileKidsIdApp/MobileKidsIdApp/ViewModels/ContactInfo.cs, src/MobileKidsIdApp/MobileKidsIdApp/ViewModels/FriendInfo.cs, src/MobileKidsIdApp/MobileKidsIdApp/ViewModels/FriendList.cs, src/MobileKidsIdApp/MobileKidsIdApp/ViewModels/ViewModelBase.cs, src/MobileKidsIdApp/MobileKidsIdApp/Views/FriendList.xaml, src/MobileKidsIdApp/MobileKidsIdApp/Views/FriendList.xaml.cs
#14, #302 Implement/fix Friends list and how contact picker is displayed.
Also get Android contact picker working with Android M and later.
=> Implement Friends

src/MobileKidsIdApp.DataAccess/MobileKidsIdApp.DataAccess.csproj, src/MobileKidsIdApp.Models.Test/MobileKidsIdApp.Models.Test.csproj, src/MobileKidsIdApp.Models/MobileKidsIdApp.Models.csproj, src/MobileKidsIdApp/MobileKidsIdApp.Android/MobileKidsIdApp.Android.csproj, src/MobileKidsIdApp/MobileKidsIdApp.iOS/MobileKidsIdApp.iOS.csproj, src/MobileKidsIdApp/MobileKidsIdApp/MobileKidsIdApp.csproj
This does not fix 332 but it gets us to the latest stable version.
=> Updated CSLA to 4.11.2.

src/MobileKidsIdApp.DataAccess/DataModels/ChildDetails.cs, src/MobileKidsIdApp.Models/ChildDetails.cs, src/MobileKidsIdApp/MobileKidsIdApp/ViewModels/BasicDetails.cs, src/MobileKidsIdApp/MobileKidsIdApp/ViewModels/ContactInfo.cs, src/MobileKidsIdApp/MobileKidsIdApp/Views/BasicDetails.xaml, src/MobileKidsIdApp/MobileKidsIdApp/Views/ChildprofileList.xaml
#349 
added manual fields for nickname, as well as contact info in case user does not want to share phone contacts, added placeholder values to clarify name fields
=> changed content of the BasicDetails page

src/MobileKidsIdApp.Models.Test/FamilyTests.cs
This unit test reproduces the problem seen in issue #332 .
=> Alter unit test to reproduce merge graph problem seen in issue #332

src/MobileKidsIdApp/MobileKidsIdApp/App.xaml.cs, src/MobileKidsIdApp/MobileKidsIdApp/Services/FamilyRepository.security.cs, src/MobileKidsIdApp/MobileKidsIdApp/Services/FamilyRepository.storage.cs, src/MobileKidsIdApp/MobileKidsIdApp/ViewModels/LoginViewModel.cs
- Fixed AES encryption using System.Net.Cryptography.AesManaged.
- This implementation replaces the dependency of PCLCrypto. 
- Generate Key based on the user's password (noodling on a password length requirement for the user as well as adding biometrics later on). 
- Added the login page back as the start screen since the password is now being used with the encryption
=> Fixed AES Encryption

src/MobileKidsIdApp/MobileKidsIdApp/ViewModels/LoginViewModel.cs
Fixed a crash that happens when you attempt to login without filling out the password field (#356)
=> Blank password login crash
